
window.countryNicknames = {
    'Afghanistan': ['Afghanistan', 'Afghan', 'افغان'],
    'Albania': ['Albania', 'Shqipëria', 'Shqipëri', 'Shqipëtarët'],
    'Algeria': ['Algeria', 'Dzayer', 'جزائري'],
    'Andorra': ['Andorra'],
    'Angola': ['Angola', 'Angolan', 'Angolano'],
    'Antarctica': ['Antarctica', 'The Ice', 'The Frozen Continent'],
    'Antigua and Barbuda': ['Antigua and Barbuda', 'Antigua'],
    'Argentina': ['Argentina', 'Arg', 'Argentine', 'Argentino'],
    'Armenia': ['Armenia', 'Hayastan', 'Հայաստան', 'Հայ'],
    'Australia': ['Australia', 'Aussie', 'The Land Down Under', 'Australian'],
    'Austria': ['Austria', 'Österreich', 'Austrian', 'Österreicher'],
    'Azerbaijan': ['Azerbaijan', 'Azərbaycan', 'Azərbaycanlı'],
    'Åland Islands': ['Åland Islands', 'Åland'],
    'Bahamas': ['Bahamas', 'The Bahamas', 'Bahamian'],
    'Bahrain': ['Bahrain', 'The Kingdom of Bahrain', 'Bahraini'],
    'Bangladesh': ['Bangladesh', 'Bangladeshi', 'বাংলাদেশ', 'বাংলাদেশি'],
    'Barbados': ['Barbados', 'Bim', 'Barbadian'],
    'Belarus': ['Belarus', 'White Rus', 'Belarusian', 'Беларусь', 'Беларус'],
    'Belgium': ['Belgium', 'Belgique', 'Belge', 'Belgian'],
    'Belize': ['Belize', 'The Jewel', 'Belizean'],
    'Benin': ['Benin', 'Dahomey', 'Beninese'],
    'Bhutan': ['Bhutan', 'Druk Yul', 'Bhutanese', 'འབྲུག་ཡུལ', 'འབྲུག'],
    'Bolivia': ['Bolivia', 'Bolivian'],
    'Bosnia and Herzegovina': ['Bosnia and Herzegovina', 'BiH', 'Bosnian'],
    'Botswana': ['Botswana', 'Motswana'],
    'Brazil': ['Brazil', 'Brasil', 'Brazilian', 'Brasileiro'],
    'British Indian Ocean Territory': ['British Indian Ocean Territory', 'BIOT'],
    'British Virgin Islands': ['British Virgin Islands', 'BVI', 'Virgin Islander'],
    'Brunei': ['Brunei', 'The Sultanate of Brunei', 'Bruneian'],
    'Bulgaria': ['Bulgaria', 'Bulgar', 'Bulgarian', 'България', 'Българин'],
    'Burkina Faso': ['Burkina Faso', 'Burkinabe'],
    'Burundi': ['Burundi', 'Burundian'],
    'Cabo Verde': ['Cabo Verde', 'Cape Verde', 'Cabo Verdean', 'Cabo-Verdiano'],
    'Cambodia': ['Cambodia', 'Kampuchea', 'Cambodian', 'Khmer', 'កម្ពុជា', 'ខ្មែរ'],
    'Cameroon': ['Cameroon', 'Cameroun', 'Cameroonian', 'Cameroonian'],
    'Canada': ['Canada', 'The Great White North', 'Canadian'],
    'Canary Islands': ['Canary Islands', 'Islas Canarias', 'Canarian'],
    'Caribbean Netherlands': ['Caribbean Netherlands', 'BES Islands'],
    'Catalonia': ['Catalonia', 'Catalunya', 'Catalan', 'Català'],
    'Central African Republic': ['Central African Republic', 'CAR', 'Central African', 'Centrafricain'],
    'Central European Free Trade Agreement': ['Central European Free Trade Agreement', 'CEFTA'],
    'Ceuta & Melilla': ['Ceuta & Melilla'],
    'Chad': ['Chad', 'Tchad', 'Chadian', 'Tchadien'],
    'Chile': ['Chile', 'Chilean', 'Chileno'],
    'China': ['China', 'People\'s Republic of China', 'Zhōngguó', 'Chinese', '中國', '中华'],
    'Colombia': ['Colombia', 'Colombian'],
    'Comoros': ['Comoros', 'Juzur Al-Qamar', 'Comorian'],
    'Congo (Democratic Republic)': ['Congo (Democratic Republic)', 'DR Congo', 'Congo-Kinshasa', 'Congolese'],
    'Congo (Republic)': ['Congo (Republic)', 'Congo-Brazzaville', 'Congolese'],
    'Costa Rica': ['Costa Rica', 'Costa Rican'],
    'Côte d\'Ivoire': ['Côte d\'Ivoire', 'Ivory Coast', 'Ivoirian', 'Ivoirien'],
    'Croatia': ['Croatia', 'Hrvatska', 'Croatian', 'Hrvat'],
    'Cuba': ['Cuba', 'Cuban'],
    'Curaçao': ['Curaçao', 'Curaçaoan', 'Curaçaoan'],
    'Cyprus': ['Cyprus', 'Kýpros', 'Cypriot', 'Κύπρος', 'Κύπριος'],
    'Czech Republic': ['Czech Republic', 'Czechia', 'Czech', 'Česká republika', 'Čech'],
    'Denmark': ['Denmark', 'Danmark', 'Danish', 'Dane'],
    'Diego Garcia': ['Diego Garcia'],
    'Djibouti': ['Djibouti', 'Jībūtī', 'Djiboutian'],
    'Dominica': ['Dominica', 'The Nature Isle', 'Dominican'],
    'Dominican Republic': ['Dominican Republic', 'DR', 'The Dominican', 'Dominican'],
    'East Timor': ['East Timor', 'Timor-Leste', 'Timorese'],
    'Ecuador': ['Ecuador', 'Ecu', 'Ecuadorian'],
    'Egypt': ['Egypt', 'Misr', 'Egyptian', 'مصري'],
    'El Salvador': ['El Salvador', 'The Savior', 'Salvadoran'],
    'England': ['England', 'English', 'Englishman', 'Brit'],
    'Equatorial Guinea': ['Equatorial Guinea', 'Guinea Ecuatorial', 'Equatoguinean'],
    'Eritrea': ['Eritrea', 'Ertra', 'Eritrean'],
    'Estonia': ['Estonia', 'Eesti', 'Estonian', 'Eestlane'],
    'Eswatini': ['Eswatini', 'Swaziland', 'Eswatini', 'Emaswati'],
    'Ethiopia': ['Ethiopia', 'Ītyōṗṗyā', 'Ethiopian', 'ኢትዮጵያ', 'ኢትዮጵያውያን'],
    'Fiji': ['Fiji', 'The Fiji Islands', 'Fijian'],
    'Finland': ['Finland', 'Suomi', 'Finnish', 'Suomalainen'],
    'France': ['France', 'La France', 'French', 'Français'],
    'French Guiana': ['French Guiana', 'Guyane', 'French Guianese', 'Guyanais'],
    'French Southern Territories': ['French Southern Territories', 'TAAF'],
    'Gabon': ['Gabon', 'The Gabonese Republic', 'Gabonese'],
    'Galicia': ['Galicia', 'Galiza', 'Galician', 'Galego'],
    'Gambia': ['Gambia', 'The Smiling Coast of Africa', 'Gambian'],
    'Georgia': ['Georgia', 'Sakartvelo', 'Georgian', 'საქართველო', 'ქართველი'],
    'Germany': ['Germany', 'Deutschland', 'German', 'Deutsche'],
    'Ghana': ['Ghana', 'The Gold Coast', 'Ghanaian'],
    'Gibraltar': ['Gibraltar', 'The Rock', 'Gibraltarian'],
    'Greece': ['Greece', 'Elláda', 'Greek', 'Ελλάδα', 'Έλληνας'],
    'Greenland': ['Greenland', 'Kalaallit Nunaat', 'Greenlander', 'Kalaallit'],
    'Grenada': ['Grenada', 'The Spice Isle', 'Grenadian'],
    'Guadeloupe': ['Guadeloupe', 'Gwadloup', 'Guadeloupean', 'Guadeloupian'],
    'Guatemala': ['Guatemala', 'The Land of Eternal Spring', 'Guatemalan'],
    'Guernsey': ['Guernsey', 'Guernesey', 'Guernseyman'],
    'Guinea': ['Guinea', 'Guinée', 'Guinean', 'Guinéen'],
    'Guinea-Bissau': ['Guinea-Bissau', 'Guiné-Bissau', 'Guinea-Bissauan', 'Bissau-Guinean'],
    'Guyana': ['Guyana', 'Co-operative Republic of Guyana', 'Guyanese'],
    'Haiti': ['Haiti', 'Haïti', 'Haitian', 'Haïtien'],
    'Heard & McDonald Islands': ['Heard & McDonald Islands'],
    'Honduras': ['Honduras', 'The Banana Republic', 'Honduran'],
    'Hong Kong': ['Hong Kong', 'Xianggang', 'Hongkonger'],
    'Hungary': ['Hungary', 'Magyarország', 'Hungarian', 'Magyar'],
    'Iceland': ['Iceland', 'Ísland', 'Icelander', 'Íslendingur'],
    'India': ['India', 'Bharat', 'Indian', 'भारत', 'भारतीय'],
    'Indonesia': ['Indonesia', 'Indonesian', 'Indonesian'],
    'Iran': ['Iran', 'Islamic Republic of Iran', 'Iranian', 'ایرانی'],
    'Iraq': ['Iraq', 'Republic of Iraq', 'Iraqi', 'عراقي'],
    'Ireland': ['Ireland', 'Éire', 'Irish', 'Éireannach'],
    'Isle of Man': ['Isle of Man', 'Ellan Vannin', 'Manx', 'Manninagh'],
    'Israel': ['Israel', 'Yisrael', 'Israeli', 'ישראל', 'ישראלי'],
    'Italy': ['Italy', 'Italia', 'Italian', 'Italiano'],
    'Jamaica': ['Jamaica', 'The Land of Wood and Water', 'Jamaican'],
    'Japan': ['Japan', 'Nippon', 'Japanese', '日本', '日本人'],
    'Jersey': ['Jersey', 'Jèrri', 'Jerseyman'],
    'Jordan': ['Jordan', 'The Hashemite Kingdom of Jordan', 'Jordanian'],
    'Kazakhstan': ['Kazakhstan', 'Qazaqstan', 'Kazakh', 'Қазақстан', 'Қазақ'],
    'Kenya': ['Kenya', 'Jamhuri ya Kenya', 'Kenyan'],
    'Kiribati': ['Kiribati', 'The Gilbert Islands', 'I-Kiribati'],
    'Korea (North)': ['Korea (North)', 'Democratic People\'s Republic of Korea', 'North Korean', '조선', '조선인'],
    'Korea (South)': ['Korea (South)', 'Republic of Korea', 'South Korean', '한국', '한국인'],
    'Kosovo': ['Kosovo', 'Kosovë', 'Kosovar'],
    'Kuwait': ['Kuwait', 'Dawlat al-Kuwait', 'Kuwaiti'],
    'Kyrgyzstan': ['Kyrgyzstan', 'Kyrgyz Republic', 'Kyrgyz', 'Кыргызстан', 'Кыргыз'],
    'Laos': ['Laos', 'Lao People\'s Democratic Republic', 'Laotian', 'ລາວ', 'ລາວປະເທດລາວ'],
    'Latvia': ['Latvia', 'Latvija', 'Latvian', 'Latvietis'],
    'Lebanon': ['Lebanon', 'Lubnān', 'Lebanese', 'لبناني'],
    'Lesotho': ['Lesotho', 'The Kingdom of Lesotho', 'Basotho'],
    'Liberia': ['Liberia', 'Republic of Liberia', 'Liberian'],
    'Libya': ['Libya', 'Dawlat Libya', 'Libyan', 'ليبي'],
    'Liechtenstein': ['Liechtenstein', 'Fürstentum Liechtenstein', 'Liechtensteiner'],
    'Lithuania': ['Lithuania', 'Lietuva', 'Lithuanian', 'Lietuvis'],
    'Luxembourg': ['Luxembourg', 'Lëtzebuerg', 'Luxembourgish', 'Luxembourger'],
    'Madagascar': ['Madagascar', 'Repoblikan\'i Madagasikara', 'Malagasy', 'Madagascan'],
    'Malawi': ['Malawi', 'The Warm Heart of Africa', 'Malawian'],
    'Malaysia': ['Malaysia', 'Malaysian', 'Malay', 'Malaysia', 'ماليزي'],
    'Maldives': ['Maldives', 'Dhivehi Raajje', 'Maldivian'],
    'Mali': ['Mali', 'République du Mali', 'Malian'],
    'Malta': ['Malta', 'Repubblika ta\' Malta', 'Maltese'],
    'Marshall Islands': ['Marshall Islands', 'Aelōn̄ in M̧ajeļ', 'Marshallese'],
    'Mauritania': ['Mauritania', 'The Islamic Republic of Mauritania', 'Mauritanian'],
    'Mauritius': ['Mauritius', 'Republic of Mauritius', 'Mauritian'],
    'Mayotte': ['Mayotte'],
    'Mexico': ['Mexico', 'United Mexican States', 'Mexican'],
    'Micronesia': ['Micronesia', 'Federated States of Micronesia', 'Micronesian'],
    'Moldova': ['Moldova', 'Republic of Moldova', 'Moldovan'],
    'Monaco': ['Monaco', 'Principality of Monaco', 'Monégasque'],
    'Mongolia': ['Mongolia', 'Монгол улс', 'Mongolian', 'Монгол'],
    'Montenegro': ['Montenegro', 'Crna Gora', 'Montenegrin', 'Црна Гора', 'Црногорски'],
    'Morocco': ['Morocco', 'The Kingdom of Morocco', 'Moroccan'],
    'Mozambique': ['Mozambique', 'Moçambique', 'Mozambican'],
    'Myanmar': ['Myanmar', 'Republic of the Union of Myanmar', 'Burmese', 'မြန်မာ', 'မြန်မာနိုင်ငံတော်'],
    'Namibia': ['Namibia', 'Republic of Namibia', 'Namibian'],
    'Nauru': ['Nauru', 'The Republic of Nauru', 'Nauruan'],
    'Nepal': ['Nepal', 'Federal Democratic Republic of Nepal', 'Nepali', 'नेपाल', 'नेपाली'],
    'Netherlands': ['Netherlands', 'The Kingdom of the Netherlands', 'Dutch', 'Nederland'],
    'New Zealand': ['New Zealand', 'Aotearoa', 'New Zealander'],
    'Nicaragua': ['Nicaragua', 'The Land of Lakes and Volcanoes', 'Nicaraguan'],
    'Niger': ['Niger', 'Republic of Niger', 'Nigerien'],
    'Nigeria': ['Nigeria', 'Federal Republic of Nigeria', 'Nigerian'],
    'North Korea': ['North Korea', 'Democratic People\'s Republic of Korea', 'North Korean', '조선', '조선인'],
    'North Macedonia': ['North Macedonia', 'Republic of North Macedonia', 'Macedonian'],
    'Northern Ireland': ['Northern Ireland', 'Irish: Tuaisceart Éireann', 'Northern Irish'],
    'Norway': ['Norway', 'Norge', 'Norwegian', 'Norsk'],
    'Oman': ['Oman', 'Saltanat Uman', 'Omani'],
    'Pakistan': ['Pakistan', 'Islamic Republic of Pakistan', 'Pakistani'],
    'Palau': ['Palau', 'Belau', 'Palauan'],
    'Palestine': ['Palestine', 'State of Palestine', 'Palestinian'],
    'Panama': ['Panama', 'The Isthmus', 'Panamanian'],
    'Papua New Guinea': ['Papua New Guinea', 'The Land of the Unexpected', 'Papua New Guinean'],
    'Paraguay': ['Paraguay', 'The Republic of Paraguay', 'Paraguayan'],
    'Peru': ['Peru', 'The Land of the Incas', 'Peruvian'],
    'Philippines': ['Philippines', 'The Pearl of the Orient Seas', 'Filipino', 'Pilipinas', 'Pilipino'],
    'Poland': ['Poland', 'Polska', 'Polish', 'Pole'],
    'Portugal': ['Portugal', 'Portuguese Republic', 'Portuguese', 'Português'],
    'Puerto Rico': ['Puerto Rico', 'Estado Libre Asociado de Puerto Rico', 'Puerto Rican'],
    'Qatar': ['Qatar', 'State of Qatar', 'Qatari'],
    'Romania': ['Romania', 'România', 'Romanian', 'Român'],
    'Russia': ['Russia', 'Russian Federation', 'Russian', 'Россия', 'Русский'],
    'Rwanda': ['Rwanda', 'The Land of a Thousand Hills', 'Rwandan'],
    'Réunion': ['Réunion', 'Reunion', 'Réunionnais'],
    'Saint Barthélemy': ['Saint Barthélemy', 'St. Barts', 'Barthélemois'],
    'Saint Kitts and Nevis': ['Saint Kitts and Nevis', 'The Federation of Saint Kitts and Nevis', 'Kittitian', 'Nevisian'],
    'Saint Lucia': ['Saint Lucia', 'Helen of the West Indies', 'Lucian'],
    'Saint Martin': ['Saint Martin', 'St. Maarten', 'Sint Maarten', 'Saint-Martinois'],
    'Saint Pierre & Miquelon': ['Saint Pierre & Miquelon', 'St. Pierre and Miquelon', 'Saint-Pierrais'],
    'Saint Vincent and the Grenadines': ['Saint Vincent and the Grenadines', 'Vincentian'],
    'Samoa': ['Samoa', 'The Treasured Islands of the South Pacific', 'Samoan'],
    'San Marino': ['San Marino', 'Republic of San Marino', 'Sammarinese'],
    'Sao Tome and Principe': ['Sao Tome and Principe', 'Democratic Republic of Sao Tome and Principe', 'São Toméan'],
    'Saudi Arabia': ['Saudi Arabia', 'Kingdom of Saudi Arabia', 'Saudi Arabian'],
    'Scotland': ['Scotland', 'Scottish', 'Scot'],
    'Senegal': ['Senegal', 'The Land of Teranga', 'Senegalese'],
    'Serbia': ['Serbia', 'Republic of Serbia', 'Serbian', 'Србија', 'Србин'],
    'Seychelles': ['Seychelles', 'Republic of Seychelles', 'Seychellois'],
    'Sierra Leone': ['Sierra Leone', 'Republic of Sierra Leone', 'Sierra Leonean'],
    'Singapore': ['Singapore', 'Republic of Singapore', 'Singaporean'],
    'Sint Maarten': ['Sint Maarten', 'Saint Martin', 'Sint Maarten', 'Saint-Martinois'],
    'Slovakia': ['Slovakia', 'Slovensko', 'Slovak', 'Slovak'],
    'Slovenia': ['Slovenia', 'Republika Slovenija', 'Slovenian', 'Slovenec'],
    'Solomon Islands': ['Solomon Islands', 'Islands of the Solomons', 'Solomon Islander'],
    'Somalia': ['Somalia', 'Federal Republic of Somalia', 'Somali', 'الصومالي'],
    'South Africa': ['South Africa', 'The Rainbow Nation', 'South African'],
    'South Georgia & South Sandwich Islands': ['South Georgia & South Sandwich Islands', 'SGSSI'],
    'South Korea': ['South Korea', 'Republic of Korea', 'South Korean', '한국', '한국인'],
    'South Sudan': ['South Sudan', 'Republic of South Sudan', 'South Sudanese'],
    'Spain': ['Spain', 'España', 'Spanish', 'Español'],
    'Sri Lanka': ['Sri Lanka', 'Democratic Socialist Republic of Sri Lanka', 'Sri Lankan'],
    'St. Helena': ['St. Helena', 'Saint Helena', 'Saint Helenian'],
    'St. Kitts and Nevis': ['St. Kitts and Nevis', 'The Federation of Saint Kitts and Nevis', 'Kittitian', 'Nevisian'],
    'St. Lucia': ['St. Lucia', 'Helen of the West Indies', 'Lucian'],
    'St. Martin': ['St. Martin', 'St. Maarten', 'Sint Maarten', 'Saint-Martinois'],
    'St. Pierre & Miquelon': ['St. Pierre & Miquelon', 'St. Pierre and Miquelon', 'Saint-Pierrais'],
    'St. Vincent and the Grenadines': ['St. Vincent and the Grenadines', 'Vincentian'],
    'Sudan': ['Sudan', 'Republic of the Sudan', 'Sudanese'],
    'Suriname': ['Suriname', 'Republic of Suriname', 'Surinamese'],
    'Svalbard & Jan Mayen': ['Svalbard & Jan Mayen'],
    'Sweden': ['Sweden', 'Sverige', 'Swedish', 'Svensk'],
    'Switzerland': ['Switzerland', 'Swiss Confederation', 'Swiss', 'Schweiz', 'Schweizer'],
    'Syria': ['Syria', 'Syrian Arab Republic', 'Syrian', 'سوري'],
    'Taiwan': ['Taiwan', 'Republic of China', 'Taiwanese', '台灣', '台灣人'],
    'Tajikistan': ['Tajikistan', 'Republic of Tajikistan', 'Tajik', 'Тоҷикистон', 'Тоҷик'],
    'Tanzania': ['Tanzania', 'United Republic of Tanzania', 'Tanzanian'],
    'Thailand': ['Thailand', 'Kingdom of Thailand', 'Thai', 'ประเทศไทย', 'ไทย'],
    'Togo': ['Togo', 'Togolese Republic', 'Togolese'],
    'Tokelau': ['Tokelau'],
    'Tonga': ['Tonga', 'Kingdom of Tonga', 'Tongan'],
    'Trinidad and Tobago': ['Trinidad and Tobago', 'The Republic of Trinidad and Tobago', 'Trinidadian', 'Tobagonian'],
    'Tunisia': ['Tunisia', 'Tunisian Republic', 'Tunisian'],
    'Turkey': ['Turkey', 'Republic of Turkey', 'Turkish', 'Türkiye', 'Türk'],
    'Turkmenistan': ['Turkmenistan', 'Turkmen', 'Түркменистан', 'Түркмен'],
    'Turks and Caicos Islands': ['Turks and Caicos Islands', 'TCI', 'Turks and Caicos Islander'],
    'Tuvalu': ['Tuvalu', 'The Ellice Islands', 'Tuvaluan'],
    'U.S. Outlying Islands': ['U.S. Outlying Islands'],
    'U.S. Virgin Islands': ['U.S. Virgin Islands', 'Virgin Islander'],
    'Uganda': ['Uganda', 'Republic of Uganda', 'Ugandan'],
    'Ukraine': ['Ukraine', 'Україна', 'Ukrainian', 'Українець'],
    'United Arab Emirates': ['United Arab Emirates', 'UAE', 'Emirati'],
    'United Kingdom': ['United Kingdom', 'UK', 'Great Britain', 'British'],
    'United States': ['United States', 'United States of America', 'USA', 'US', 'U.S.', 'U.S.A.', 'America', 'American'],
    'Uruguay': ['Uruguay', 'Eastern Republic of Uruguay', 'Uruguayan'],
    'Uzbekistan': ['Uzbekistan', 'Republic of Uzbekistan', 'Uzbek', 'Ўзбекистон', 'Ўзбек'],
    'Vanuatu': ['Vanuatu', 'The Republic of Vanuatu', 'Vanuatuan'],
    'Vatican City': ['Vatican City', 'Vatican City State', 'Vatican'],
    'Venezuela': ['Venezuela', 'Bolivarian Republic of Venezuela', 'Venezuelan'],
    'Vietnam': ['Vietnam', 'Socialist Republic of Vietnam', 'Vietnamese', 'Việt Nam', 'Việt'],
    'Wales': ['Wales', 'Welsh', 'Cymru'],
    'Wallis and Futuna': ['Wallis and Futuna', 'Territory of the Wallis and Futuna Islands', 'Wallisian'],
    'Western Sahara': ['Western Sahara', 'Sahrawi Arab Democratic Republic', 'Sahrawi'],
    'Yemen': ['Yemen', 'Republic of Yemen', 'Yemeni', 'يمني'],
    'Zambia': ['Zambia', 'Republic of Zambia', 'Zambian'],
    'Zimbabwe': ['Zimbabwe', 'Republic of Zimbabwe', 'Zimbabwean']
    };

// export default countryNicknames; // NEEDS TO BE FIXED